server:
  port: 8091

spring:
  application:
    name: admin-dashboard-service
  datasource:
    url: jdbc:mysql://localhost:3306/admin_dashboard_service?createIfNotExist=true
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
