server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/chat_service
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  application:
    name: chat-service
openai:
  api:
    key: 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
    url: https://openrouter.ai/api/v1/chat/completions

product:
  service-url: http://api-gateway:8080/api/products/ai/search

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

