server:
  port: 8090

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/inventory_service
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka