server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  application:
    name: order-service
payment-service:
  url: http://PAYMENT-SERVICE
