server:
  port: 8085

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/product_service?createDatabaseIfNotExist=true
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
logging:
  level:
    root: INFO
    com.product.productservice: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /logs/product-service.log