server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/review_service
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: review-service
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.server: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka