spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
<<<<<<< HEAD
#  cloud:
#    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true # <-- THÊM DÒNG NÀY
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5173"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
#            allowCredentials: true
#  cloud:
#    config:
#      uri: http://config-server:8888
=======
  cloud:
    config:
      uri: http://config-server:8888
>>>>>>> 850e78f10f8036491a7a7b90aa61369c721ea211
