eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

spring:
<<<<<<< HEAD
  application:
    name: product-service
  config:
    import: "optional:configserver:"
#    cloud:
#        config:
#            uri: http://config-server:8888
=======
    application:
        name: product-service
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://config-server:8888
>>>>>>> 850e78f10f8036491a7a7b90aa61369c721ea211
