server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cartdb?useSSL=false&serverTimezone=UTC
    username: root
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
