server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file:/config-repo
           search-locations: file:///D:/DH17KTPM/HK2_2024_2025/KTTKPM/Project_Medical/Medical_Supplies_BE/config-repo
