server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #          search-locations: file:/config-repo
          search-locations: file:///D:\WorkSpace\MedicalSupplies\Medical_Supplies_BE\config-repo
